# Generated by Django 3.2.4 on 2021-06-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.TextField()),
                ('artist', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('PA', 'Painting'), ('SC', 'Sculptures'), ('DR', 'Drawings'), ('AB', 'Abstract'), ('IN', 'Installations'), ('PH', 'Photography')], default='PA', max_length=2)),
            ],
        ),
    ]
